### ISSUE TITLE
Update packages source_url and make it configurable

### ISSUE THREAD

**Issue by vide** [hfm/puppet-mha#27]
Currently the source_url variable is hardcoded to `https://72003f4c60f5cc941cd1c7d448fc3c99e0aebaa8.googledrive.com/host/0B1lu97m8-haWeHdGWXp0YVVUSlk/${rpm}` which currently results in a broken URL (that google drive doesn't exist anymore). Moreover, it's not easy to overwrite it because it's not parametrized, resulting right now in a broken module under (at least) CentOS 7

**Comment by hfm** [comment]
This issue has been fixed by #24. You'd update puppet-mha module.

**Comment by vide** [comment]
Ooops, sorry and thanks!
